# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.cache/wt [current_project]
set_property parent.project_path E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/ip/prom/sort.coe
add_files E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/ip/dram/dmem32.coe
read_verilog -library xil_defaultlib {
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/EX_MEM.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/ID_EX.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/IF_ID.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/MEM_WB.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/control.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/dmem.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/exe.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/hazarddect.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/idecode.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/ifetch.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/writeback.v
  E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/new/MIPS_1.v
}
read_ip -quiet E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/ip/prom/prom.xci
set_property used_in_implementation false [get_files -all e:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/ip/prom/prom_ooc.xdc]

read_ip -quiet E:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/ip/dram/dram.xci
set_property used_in_implementation false [get_files -all e:/course/computer_architecture/MIPS1/MIPS_1/MIPS_1.srcs/sources_1/ip/dram/dram_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MIPS_1 -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MIPS_1.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MIPS_1_utilization_synth.rpt -pb MIPS_1_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
